### ISSUE TITLE
Fixes to Open Task `Types`

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov-front-end#179]
**Describe the bug**

**To Reproduce**

1. View Open Tasks for GSA https://code.gov/open-tasks?&agencies=GSA&page=1&size=10
2.  Take a look a the Type meta data for `Reduce Image Sizes` and several other tasks. The type is listed as `good`. 

**Expected behavior**

Type should be `good first issue`.

**Screenshots**

<img width="971" alt="Screen Shot 2019-05-07 at 5 34 16 PM" src="https://user-images.githubusercontent.com/2197515/57335070-8b6a3980-70ef-11e9-8ea6-73d09d0de356.png">
<img width="286" alt="Screen Shot 2019-05-07 at 5 34 24 PM" src="https://user-images.githubusercontent.com/2197515/57335071-8b6a3980-70ef-11e9-86e0-189d7dc29e1f.png">
<img width="334" alt="Screen Shot 2019-05-07 at 5 38 14 PM" src="https://user-images.githubusercontent.com/2197515/57335072-8b6a3980-70ef-11e9-8b7a-2b044db5127a.png">

**Additional context**

**Comment by sdhungel4** [comment]
Looks like this issue is already resolved so should not be listed under open issues. Thanks!

**Comment by saracope** [comment]
Thanks for taking a look. I'm still seeing the issues on a few more tasks. 

Screenshot:
<img width="805" alt="Screen Shot 2019-05-18 at 5 30 56 PM" src="https://user-images.githubusercontent.com/2197515/57975201-c3e10180-7992-11e9-8c3a-e3383a030a04.png">

**Comment by saracope** [comment]
<img width="262" alt="Screen Shot 2019-05-30 at 7 35 45 AM" src="https://user-images.githubusercontent.com/2197515/58630512-a1fa4f80-82ad-11e9-84dd-65d9a4f302aa.png">

This is what we're getting back from the API.

**Comment by saracope** [comment]
There could be several [`type`](https://github.com/GSA/code-gov/blob/master/HelpWanted.md#issue-type) labels on a single issue. It looks like we're only grabbing one of them, and in these cases that is `good`  for `good first issue`. 
Need to have a convo with back-end engineering about the API.

**Comment by jcastle** [comment]
Fixed `good first issue` to display in project card. However, need to update front-end for filtering. Issue #345
